server:
  port: 8080

spring:
  application:
    name: usuarios-service
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}
  issuer: ${JWT_ISSUER:miapp}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  health:
    probes:
      enabled: true
    status:
      http-mapping:
        DOWN: 503
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-},%X{spanId:-}]" 