server:
  port: 8082
spring:
  application:
    name: usuarios-service
  security:
    user:
      name: admin
      password: admin123

  datasource:
    url: jdbc:postgresql://ep-withered-king-aa21vv8q-pooler.westus3.azure.neon.tech:5432/neondb?user=neondb_owner&password=npg_0gnbkuv5IWlH&sslmode=require
    username: neondb_owner
    password: npg_0gnbkuv5IWlH
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    enabled: false

jwt:
  secret: "+7xPjMy3ShEYQClRLDpvwcy6GjDADONvh10c4iMxFrU="
  expiration: 3600000  # 1 hora en milisegundos
  issuer: miapp

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

# Tracing
management:
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
              include: "*"

logging:
  level:
    root: debug
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-},%X{spanId:-}]"