apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: gcr.io/gcp-despliegue-desarrollo/usuarios-service:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: usuarios-config
            - secretRef:
                name: usuarios-secrets