apiVersion: v1
kind: Secret
metadata:
  name: usuarios-secrets
type: Opaque
stringData:
  SECURITY_USER_NAME: admin
  SECURITY_USER_PASSWORD: admin123
  DB_USERNAME: neondb_owner
  DB_PASSWORD: npg_0gnbkuv5IWlH
  JWT_SECRET: "+7xPjMy3ShEYQClRLDpvwcy6GjDADONvh10c4iMxFrU="
  JWT_EXPIRATION: "3600000"