name: Deploy Usuarios Service

on:
  push:
    branches:
      - main
      - test-workflow

env:
  SERVICE_NAME: usuarios-service
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/usuarios-service
  K8S_DIR: kubernetes


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test
        run: |
          mvn clean package
          mvn test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:latest .
          docker push ${{ env.DOCKER_IMAGE }}:latest


      
  deploy-to-gke:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and test
        run: |
          mvn clean package
          mvn test
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: desarrollo-cluster
          location: us-central1
          project_id: gcp-despliegue-desarrollo

      - name: Deploy to GKE
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          envsubst < ${{ env.K8S_DIR }}/deployment.yml > ${{ env.K8S_DIR }}/deployment-processed.yml
          kubectl apply -f ${{ env.K8S_DIR }}/deployment-processed.yml
          kubectl apply -f ${{ env.K8S_DIR }}/service.yml
          kubectl rollout status deployment/${{ env.SERVICE_NAME }}-deployment --timeout=120s
      - name: Debug deployment failure
        if: failure()
        run: |
          echo "==== PODS ===="
          kubectl get pods -o wide
          
          echo "==== DESCRIBE POD ===="
          kubectl describe pod $(kubectl get pod -l app=${{ env.SERVICE_NAME }} -o jsonpath="{.items[0].metadata.name}")
          
          echo "==== LOGS ===="
          kubectl logs $(kubectl get pod -l app=${{ env.SERVICE_NAME }} -o jsonpath="{.items[0].metadata.name}")